{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.redis.fullname" . }}-secret
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  # Empty secret, can be used for Redis password if needed
  password: ""
{{- end }}
