{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.redis.fullname" . }}
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "harbor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
