apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-secret
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.harbor.adminPassword | b64enc | quote }}
  secret-key: {{ .Values.harbor.secretKey | b64enc | quote }}
