{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.postgresql.fullname" . }}-secret
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  username: {{ .Values.postgresql.credentials.username | b64enc | quote }}
  password: {{ .Values.postgresql.credentials.password | b64enc | quote }}
  database: {{ .Values.postgresql.credentials.database | b64enc | quote }}
{{- end }}
